spring:
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
      password: cXdlcnR5b3Bhc2R2Ym4=
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: z7J.6q
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

security:
  jwt:
    secret: a2prZW5mamtlbmNka2VkbmphbkpOREVKRE5sbmRqbndsbk5MRFNOTm5qbkpOam5sbkxKTm5iaFZVVko=
    access: 3600000
    refresh: 2592000000
springdoc:
  override-with-generic-response: false