spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: a2prZW5mamtlbmNka2VkbmphbkpOREVKRE5sbmRqbndsbk5MRFNOTm5qbkpOam5sbkxKTm5iaFZVVko=
    access: 3600000
    refresh: 2592000000